name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive
        run: git archive --format=zip --output="TelegramContactBot-${GITHUB_REF_NAME}.zip" HEAD

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "TelegramContactBot-*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
